In [1]:
# SVM Classification
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.preprocessing import StandardScaler

from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report


from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score

In [13]:
import pandas as pd
df = pd.read_csv(r"C:\Users\DELL\Desktop\bharath's file\DS\csv\forestfires.csv")
df.head()

,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,...,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep,size_category
0,mar,fri,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,...,0,0,0,0,1,0,0,0,0,small
1,oct,tue,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,...,0,0,0,0,0,0,0,1,0,small
2,oct,sat,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,...,0,0,0,0,0,0,0,1,0,small
3,mar,fri,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,...,0,0,0,0,1,0,0,0,0,small
4,mar,sun,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,...,0,0,0,0,1,0,0,0,0,small

In [4]:
X = df.drop(['month','day','size_category'],axis = 1)
Y = df['size_category']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size = 0.3)

In [8]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((361, 28), (361,), (156, 28), (156,))

# Grid Search CV

In [20]:
clf = SVC()
param_grid = [{'kernel':['rbf'],'gamma':[50,5,10,0.5],'C':[15,14,13,12,11,10,0.1,0.001] }]
gsv = GridSearchCV(clf,param_grid,cv=10)
gsv.fit(X_train,y_train)

GridSearchCV(cv=10, estimator=SVC(),
             param_grid=[{'C': [15, 14, 13, 12, 11, 10, 0.1, 0.001],
                          'gamma': [50, 5, 10, 0.5], 'kernel': ['rbf']}])

In [10]:
gsv.best_params_ , gsv.best_score_

({'C': 15, 'gamma': 0.5, 'kernel': 'rbf'}, 0.7286036036036037)

In [14]:
clf = SVC(C= 15, gamma = 0.5)
clf.fit(X_train , y_train)
y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)

Accuracy = 76.92307692307693

array([[  1,  36],
       [  0, 119]], dtype=int64)

# classification

In [16]:
clf = SVC(C= 15, gamma = 50)
clf.fit(X , Y)
Y_pred = clf.predict(X)

In [17]:
Y_pred

array(['small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'large', 'large', 'large', 'large', 'large', 'large', 'large',
       'large', 'large', 'large', 'large', 'large', 'large', 'large',
       'large', 'large', 'large', 'large', 'large', 'large', 'large',
       'large', 'large', 'large', 'large', 'large', 'large', 'large',
       'large', 'large', 'large', 'large', 'large', 'large', 'large',
       'large', 'large', 'large', 'large', 'large', 'large', 'large',
       'large', 'large', 'large', 'large', 'large', 'large', 'large',
       'large', 'large', 'large', 'large', 'large', 'large', 'large',
       'large', 'small', 'small', 'small', 'large', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'large', 'small', 'large', 'small', 'small',
       'small', 'large', 'small', 'small', 'small', 'large', 'small',
       'small', 'small', 'small', 'small', 'small', 'large', 'small',
       'large', 'large', 'small', 'large', 'large', 'large', 'large',
       'large', 'large', 'small', 'small', 'large', 'small', 'small',
       'small', 'small', 'small', 'small', 'large', 'small', 'large',
       'large', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'large', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'large', 'large',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'large', 'large', 'large', 'small', 'small', 'small',
       'small', 'large', 'large', 'small', 'small', 'small', 'small',
       'small', 'large', 'small', 'large', 'small', 'small', 'small',
       'small', 'large', 'small', 'small', 'small', 'large', 'small',
       'small', 'small', 'large', 'small', 'small', 'small', 'small',
       'small', 'large', 'small', 'small', 'large', 'small', 'large',
       'small', 'small', 'small', 'large', 'large', 'small', 'large',
       'small', 'small', 'large', 'large', 'small', 'large', 'large',
       'large', 'large', 'small', 'large', 'small', 'large', 'large',
       'large', 'small', 'small', 'large', 'small', 'small', 'small',
       'small', 'large', 'small', 'small', 'small', 'large', 'small',
       'small', 'small', 'large', 'small', 'small', 'small', 'small',
       'small', 'small', 'large', 'large', 'small', 'small', 'small',
       'large', 'small', 'large', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'large', 'small', 'large',
       'small', 'small', 'small', 'small', 'large', 'small', 'small',
       'small', 'small', 'small', 'large', 'small', 'small', 'small',
       'small', 'small', 'large', 'large', 'small', 'small', 'small',
       'small', 'small', 'large', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'large', 'small', 'small', 'large',
       'large', 'small', 'large', 'small', 'large', 'large', 'small',
       'small', 'large', 'small', 'large', 'small', 'small', 'small',
       'small', 'large', 'small', 'small', 'large', 'large', 'small',
       'small', 'small', 'small', 'large', 'large', 'small', 'small',
       'large', 'large', 'large', 'small', 'small', 'small', 'small',
       'large', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'large', 'large', 'large', 'small', 'small'], dtype=object)

In [18]:
df['CATEGORY'] = Y_pred
df

,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,...,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep,size_category,CATEGORY
0,mar,fri,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,...,0,0,0,1,0,0,0,0,small,small
1,oct,tue,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,...,0,0,0,0,0,0,1,0,small,small
2,oct,sat,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,...,0,0,0,0,0,0,1,0,small,small
3,mar,fri,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,...,0,0,0,1,0,0,0,0,small,small
4,mar,sun,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,...,0,0,0,1,0,0,0,0,small,small
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512,aug,sun,81.6,56.7,665.6,1.9,27.8,32,2.7,0.0,...,0,0,0,0,0,0,0,0,large,large
513,aug,sun,81.6,56.7,665.6,1.9,21.9,71,5.8,0.0,...,0,0,0,0,0,0,0,0,large,large
514,aug,sun,81.6,56.7,665.6,1.9,21.2,70,6.7,0.0,...,0,0,0,0,0,0,0,0,large,large
515,aug,sat,94.4,146.0,614.7,11.3,25.6,42,4.0,0.0,...,0,0,0,0,0,0,0,0,small,small
516,nov,tue,79.5,3.0,106.7,1.1,11.8,31,4.5,0.0,...,0,0,0,0,0,1,0,0,small,small

In [19]:
result1 = df.groupby(df.CATEGORY).mean()
result1

,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area,dayfri,...,monthdec,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep
CATEGORY,,,,,,,,,,,,,,,,,,,,,
large,90.845324,114.535252,555.879856,8.956115,18.946763,43.071942,4.192086,0.046043,45.495971,0.151079,...,0.057554,0.043165,0.000000,0.064748,0.021583,0.086331,0.007194,0.000000,0.028777,0.366906
small,90.570899,109.525397,545.020370,9.045767,18.867989,44.735450,3.953439,0.012698,0.841561,0.169312,...,0.002646,0.037037,0.005291,0.060847,0.037037,0.111111,0.002646,0.002646,0.029101,0.320106